  services:
    banking_migration_sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: banking_migration_sql_container
        ports:
            - "1431:1433" 
        environment:
          - ACCEPT_EULA=y
          - MSSQL_SA_PASSWORD=AVeryComplex123Password!
          - MSSQL_PID=Express